//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pball.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PBallRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PBallRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pball.Resources.PBallRes", typeof(PBallRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exist.
        /// </summary>
        public static string _AlreadyExist {
            get {
                return ResourceManager.GetString("_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already taken.
        /// </summary>
        public static string _AlreadyTaken {
            get {
                return ResourceManager.GetString("_AlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] date is bigger than [{1}].
        /// </summary>
        public static string _DateIsBiggerThan_ {
            get {
                return ResourceManager.GetString("_DateIsBiggerThan_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid email.
        /// </summary>
        public static string _IsNotAValidEmail {
            get {
                return ResourceManager.GetString("_IsNotAValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string _IsRequired {
            get {
                return ResourceManager.GetString("_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length should be between {1} and {2}.
        /// </summary>
        public static string _LengthShouldBeBetween_And_ {
            get {
                return ResourceManager.GetString("_LengthShouldBeBetween_And_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} maximum length is {1}..
        /// </summary>
        public static string _MaxLengthIs_ {
            get {
                return ResourceManager.GetString("_MaxLengthIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} maximum value is {1}.
        /// </summary>
        public static string _MaxValueIs_ {
            get {
                return ResourceManager.GetString("_MaxValueIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minimum length is {1}..
        /// </summary>
        public static string _MinLengthIs_ {
            get {
                return ResourceManager.GetString("_MinLengthIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minimum value is {1}.
        /// </summary>
        public static string _MinValueIs_ {
            get {
                return ResourceManager.GetString("_MinValueIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be equal to {1}.
        /// </summary>
        public static string _ShouldBeEqualTo_ {
            get {
                return ResourceManager.GetString("_ShouldBeEqualTo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be null or empty.
        /// </summary>
        public static string _ShouldNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("_ShouldNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value should be between {1} and {2}.
        /// </summary>
        public static string _ValueShouldBeBetween_And_ {
            get {
                return ResourceManager.GetString("_ValueShouldBeBetween_And_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic email.
        /// </summary>
        public static string AutomaticEmail {
            get {
                return ResourceManager.GetString("AutomaticEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add {0}: Error: {1}.
        /// </summary>
        public static string CouldNotAdd_Error_ {
            get {
                return ResourceManager.GetString("CouldNotAdd_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete {0}: Error: {1}.
        /// </summary>
        public static string CouldNotDelete_Error_ {
            get {
                return ResourceManager.GetString("CouldNotDelete_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0} with {1} equal {2}.
        /// </summary>
        public static string CouldNotFind_With_Equal_ {
            get {
                return ResourceManager.GetString("CouldNotFind_With_Equal_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not modify {0}: Error: {1}.
        /// </summary>
        public static string CouldNotModify_Error_ {
            get {
                return ResourceManager.GetString("CouldNotModify_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date issued.
        /// </summary>
        public static string DateIssued {
            get {
                return ResourceManager.GetString("DateIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Error_ {
            get {
                return ResourceManager.GetString("Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language not selected.
        /// </summary>
        public static string LanguageNotSelected {
            get {
                return ResourceManager.GetString("LanguageNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary code to change your password.
        /// </summary>
        public static string TemporaryCodeToChangeYourPassword {
            get {
                return ResourceManager.GetString("TemporaryCodeToChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login as {0} with provided password.
        /// </summary>
        public static string UnableToLoginAs_WithProvidedPassword {
            get {
                return ResourceManager.GetString("UnableToLoginAs_WithProvidedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown server error.
        /// </summary>
        public static string UnknownServerError {
            get {
                return ResourceManager.GetString("UnknownServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have authorization.
        /// </summary>
        public static string YouDoNotHaveAuthorization {
            get {
                return ResourceManager.GetString("YouDoNotHaveAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be a league administrator to generate temp code.
        /// </summary>
        public static string YouNeedToBeLeagueAdminToGenerateTempCode {
            get {
                return ResourceManager.GetString("YouNeedToBeLeagueAdminToGenerateTempCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        public static string YourPasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChanged", resourceCulture);
            }
        }
    }
}
