/*
 * Auto generated C:\CSSPTools\src\codegen\GenerateAngularEnums\bin\Debug\net6.0\GenerateAngularEnums.exe
 *
 * Do not edit this file.
 *
 */

import { AppLanguageService } from 'src/app/services/app/app-language.service';
import { EnumIDAndText } from 'src/app/models/EnumIDAndText.model';

export enum LanguageEnum {
    en = 1,
    fr = 2,
}

export function GetLanguageEnum(): typeof LanguageEnum
{
  return LanguageEnum;
}

export function LanguageEnum_GetOrderedText(appLanguageService: AppLanguageService): EnumIDAndText[] {
    let enumTextOrderedList: EnumIDAndText[] = [];
    if (appLanguageService.Language == LanguageEnum.fr) {
        enumTextOrderedList.push({ EnumID: 1, EnumText: 'en' });
        enumTextOrderedList.push({ EnumID: 2, EnumText: 'fr' });
    }
    else {
        enumTextOrderedList.push({ EnumID: 1, EnumText: 'en' });
        enumTextOrderedList.push({ EnumID: 2, EnumText: 'fr' });
    }

    return enumTextOrderedList.sort((a, b) => a.EnumText.localeCompare(b.EnumText));
}

export function LanguageEnum_GetIDText(enumID: number, appLanguageService: AppLanguageService): string {
    let LanguageEnumText: string = '';
    LanguageEnum_GetOrderedText(appLanguageService).forEach(e => {
        if (e.EnumID == enumID) {
            LanguageEnumText = e.EnumText;
            return false;
        }
        return LanguageEnumText;
    });

    return LanguageEnumText;
}
